# Generated by Django 3.1.7 on 2021-04-03 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='titulo')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='modificado')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('content', models.TextField(verbose_name='contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./categorias', verbose_name='imagen')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publicado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='modificado')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='creado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categories', models.ManyToManyField(to='blog.Category', verbose_name='categorias')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-created'],
            },
        ),
    ]
